version: "3.9"
services:
  zepellin:
    build: .
    ports:
    - "8080:8080"
    - "8081:8081"
    links:
    - kafka
    networks:
    - workshop
    depends_on:
    - kafka
  kafka:
    image: lensesio/fast-data-dev
    networks:
    - workshop
  producer:
    image: rnavarro23/fake-data-producer
    networks: 
    - workshop
    links:
    - kafka
    depends_on:
    - kafka
  druid:
    image: apache/druid:0.20.2
    networks: 
    - workshop
    links:
    - kafka
    ports:
    - "8888:8888"
networks:
    workshop: {}